### ISSUE TITLE
Where to add charset conversions

### ISSUE THREAD

**Issue by JoachimTuchel** [noha/mustache#4]
I would like to add character set conversion to mustache for my port on VA Smalltalk.

Background: VA Smalltalk doesn't natively speak UTF-8, so I'd like to convert all insertions into a template to UTF-8.

So I wonder what a good place for such an extension would be. My first impulse would be to add an inst var to MustacheTemplate, maybe named #charSet. 
Then I think the next best thing to do would be to add a parameter to all implementors of #mustacheLookup: which is either nil or the charset to convert to.

The problem: a MustachePart doesn't know the MustacheTemplate, so there is no way of asking a template for the value of its charSet when it is trying to fill in  text....

Any ideas?

**Comment by noha** [comment]
Wow, I've just seen this issue now. Is this still a thing? I think not. But mustache is not working on bytes but on strings so I do not know why it should care about about encoding.

**Comment by JoachimTuchel** [comment]
Norbert,
it is still a thing in my port of it on VAST ;-) We store values in or DB in ISO-8559-15 and use Mustache for documents in both ISO-8559-15 as well as UTF-8. So our mustache templates are in UTF-8 and need to fill in values delivered in iso-8559-15.

I implemented "something" that works on VAST, we initiialize a mustacheTemplate with a charset and have it convert values before filling them in. If anybody thinks that's interesting, I am happy to share my implementation. Due to platform differences, I am not sure how I could do that via a PR...

The main idea is that MustachePart and MustacheVisitor have an instance variable named charSet. 
The magic happens in MustacheToken>>#valueInContext:

valueInContext: anObject
	"lookup to token, perfrom value on it in case we have a block and 
	finally convert it to string"

	^(self lookupInContext: anObject)
		ifNotNil: [:object | | result |
			"In Pharo, this ifTrue/ifFalse is not necessary, but in VAST, Characters return their numeric value to #value and so the result is a number instead of the Character"

			result := (object isCharacter ifTrue: [object] ifFalse: [object value]) asString.
			^self charSet ifNil: [result] ifNotNil: [:chs | result convertToCodePage: chs]  "<---- this converts the value to insert"

			]
		ifNil: ['']


I'm attching a fileout of my changes from Version NorbertHartl.33 which I used for porting to VAST. As you can see, there is not much I added, in the end it is just a way to transport the charSet down to the visitor: for when it does the actual filling in. 

I know this is probably more like an external addition to Mustache as it comes from other platforms, and maybe nobody else than me ever has the problem, so feel free to ignore my suggestion ;-)

[MustacheCompositePart.txt](https://github.com/noha/mustache/files/10577554/MustacheCompositePart.txt)
[MustachePart.txt](https://github.com/noha/mustache/files/10577555/MustachePart.txt)
[MustacheTemplate.txt](https://github.com/noha/mustache/files/10577556/MustacheTemplate.txt)
[MustacheToken.txt](https://github.com/noha/mustache/files/10577557/MustacheToken.txt)
[MustacheVisitor.txt](https://github.com/noha/mustache/files/10577558/MustacheVisitor.txt)

**Comment by noha** [comment]
Thanks for the reply. But I can just repeat what I've said. Mustache acts on characters and they don't have an encoding. Encoding happens when writing characters to outside the image or read them from outside of the image. So you need to read the template and partials in the proper encoding and then you are done. So you can read a template in utf-8 and a partial in latin-1. Both are converted to characters and it works and then you write it out with another encoding. 
I'm sure I just miss a shortcoming of Vast here that forces you to do that. But this is conceptually wrong so I'm not willing to add that.
